export class VolantesDonacion {
	idVolanteDonacionSangre?: number;
	desUnidadMedicaHospitalaria?: string;
	fecEfec?: string;
	idNombreBancoSangre?: number;
	nombreBancoSangre?: string;
	timHoraInicialAtencion?: string;
	timHoraFinalAtencion?: string;
	desCodigoPostal?: string;
	idEstado?: number;
	nombreEstado?: string;
	idDelegacionMunicipio?: string;
	nombreDelegacionMunicipio?: string;
	idCiudad?: number;
	nombreCiudad?: string;
	nomColonia?: string;
	nomCalle?: string;
	numExterior?: number;
	numInterior?: string;
	nomPaciente?: string;
	desNssAgregado?: string;
	idServicio?: number;
	nombreServicio?: string;
	fecInternamiento?: string;
	fecCirugia?: string;
	numTelefonoPaciente?: string;
	nomTrabajadorSocial?: string;
	desMatriculaTrabajadorSocial?:string;
	numTelefonoTrabajadorSocial?:string;
	desObservaciones?:string;
	nss?:string;
	nssCompleto?:string;
	tipoSangre?:string;
}